[workspace]
members = [
    "crates/runen-core-ir",
    "crates/runen-core-lowering",
    "crates/runen-exec-oracle",
    "crates/runen-hir",
    "crates/runen-numeric-oracle",
    "crates/runen-reference",
    "crates/runen-syntax",
    "tools/xtask",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "GPL-3.0-only"

[workspace.lints.rust]
unsafe_code = "forbid"
unused_lifetimes = "deny"
unused_qualifications = "deny"
