[package]
name = "runen-core-lowering"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
runen-core-ir = { path = "../runen-core-ir" }
runen-hir = { path = "../runen-hir" }

[dev-dependencies]
runen-reference = { path = "../runen-reference" }
runen-syntax = { path = "../runen-syntax" }

[lints]
workspace = true
