use runen_numeric_oracle::{
    BinaryFormat, BinaryValueFixture, ExactDyadic, RoundedBinaryValue, Sign, round_dyadic,
};

// Finite expected values below are independently generated by GNU MPFR 4.2.2.
// The checked regeneration program is `../reference/generate_sine_mpfr.c`.
// MPFR is verification instrumentation only; Runen semantics remain owned by
// `spec/language/core/numerics/floating-point.md`.
//
// Generation uses target precision p, MPFR emin = Runen emin - p + 2,
// MPFR emax = Runen emax + 1, exact dyadic inputs, `mpfr_sin` with
// MPFR_RNDN, and `mpfr_subnormalize` with the returned ternary value and
// MPFR_RNDN. Normal `cargo validate` does not execute or depend on MPFR.

const POS: Sign = Sign::Positive;
const NEG: Sign = Sign::Negative;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct ReferenceCase {
    input: ExactDyadic,
    expected: RoundedBinaryValue,
}

impl ReferenceCase {
    const fn subnormal(
        input_sign: Sign,
        input_magnitude: u128,
        input_exponent: i32,
        expected_sign: Sign,
        expected_significand: u128,
    ) -> Self {
        Self {
            input: ExactDyadic::from_parts(input_sign, input_magnitude, input_exponent),
            expected: RoundedBinaryValue::Subnormal {
                sign: expected_sign,
                significand: expected_significand,
            },
        }
    }

    const fn normal(
        input_sign: Sign,
        input_magnitude: u128,
        input_exponent: i32,
        expected_sign: Sign,
        expected_significand: u128,
        expected_exponent: i32,
    ) -> Self {
        Self {
            input: ExactDyadic::from_parts(input_sign, input_magnitude, input_exponent),
            expected: RoundedBinaryValue::Normal {
                sign: expected_sign,
                significand: expected_significand,
                exponent: expected_exponent,
            },
        }
    }
}

// Generated with GNU MPFR 4.2.2; see reference/generate_sine_mpfr.c.
// BEGIN GENERATED SINE REFERENCE CORPUS
const TINY_FINITE_CASES: &[ReferenceCase] = &[
    ReferenceCase::subnormal(POS, 1, -5, POS, 1),
    ReferenceCase::subnormal(POS, 2, -5, POS, 2),
    ReferenceCase::subnormal(POS, 3, -5, POS, 3),
    ReferenceCase::subnormal(POS, 4, -5, POS, 4),
    ReferenceCase::subnormal(POS, 5, -5, POS, 5),
    ReferenceCase::subnormal(POS, 6, -5, POS, 6),
    ReferenceCase::subnormal(POS, 7, -5, POS, 7),
    ReferenceCase::normal(POS, 8, -5, POS, 8, -2),
    ReferenceCase::normal(POS, 9, -5, POS, 9, -2),
    ReferenceCase::normal(POS, 10, -5, POS, 10, -2),
    ReferenceCase::normal(POS, 11, -5, POS, 11, -2),
    ReferenceCase::normal(POS, 12, -5, POS, 12, -2),
    ReferenceCase::normal(POS, 13, -5, POS, 13, -2),
    ReferenceCase::normal(POS, 14, -5, POS, 14, -2),
    ReferenceCase::normal(POS, 15, -5, POS, 14, -2),
    ReferenceCase::normal(POS, 8, -4, POS, 15, -2),
    ReferenceCase::normal(POS, 9, -4, POS, 9, -1),
    ReferenceCase::normal(POS, 10, -4, POS, 9, -1),
    ReferenceCase::normal(POS, 11, -4, POS, 10, -1),
    ReferenceCase::normal(POS, 12, -4, POS, 11, -1),
    ReferenceCase::normal(POS, 13, -4, POS, 12, -1),
    ReferenceCase::normal(POS, 14, -4, POS, 12, -1),
    ReferenceCase::normal(POS, 15, -4, POS, 13, -1),
    ReferenceCase::normal(POS, 8, -3, POS, 13, -1),
    ReferenceCase::normal(POS, 9, -3, POS, 14, -1),
    ReferenceCase::normal(POS, 10, -3, POS, 15, -1),
    ReferenceCase::normal(POS, 11, -3, POS, 8, 0),
    ReferenceCase::normal(POS, 12, -3, POS, 8, 0),
    ReferenceCase::normal(POS, 13, -3, POS, 8, 0),
    ReferenceCase::normal(POS, 14, -3, POS, 8, 0),
    ReferenceCase::normal(POS, 15, -3, POS, 15, -1),
    ReferenceCase::normal(POS, 8, -2, POS, 15, -1),
    ReferenceCase::normal(POS, 9, -2, POS, 12, -1),
    ReferenceCase::normal(POS, 10, -2, POS, 10, -1),
    ReferenceCase::normal(POS, 11, -2, POS, 12, -2),
    ReferenceCase::subnormal(POS, 12, -2, POS, 5),
    ReferenceCase::subnormal(POS, 13, -2, NEG, 3),
    ReferenceCase::normal(POS, 14, -2, NEG, 11, -2),
    ReferenceCase::normal(POS, 15, -2, NEG, 9, -1),
    ReferenceCase::normal(POS, 8, -1, NEG, 12, -1),
    ReferenceCase::normal(POS, 9, -1, NEG, 8, 0),
    ReferenceCase::normal(POS, 10, -1, NEG, 15, -1),
    ReferenceCase::normal(POS, 11, -1, NEG, 11, -1),
    ReferenceCase::normal(POS, 12, -1, NEG, 9, -2),
    ReferenceCase::subnormal(POS, 13, -1, POS, 7),
    ReferenceCase::normal(POS, 14, -1, POS, 11, -1),
    ReferenceCase::normal(POS, 15, -1, POS, 15, -1),
    ReferenceCase::subnormal(NEG, 1, -5, NEG, 1),
    ReferenceCase::subnormal(NEG, 2, -5, NEG, 2),
    ReferenceCase::subnormal(NEG, 3, -5, NEG, 3),
    ReferenceCase::subnormal(NEG, 4, -5, NEG, 4),
    ReferenceCase::subnormal(NEG, 5, -5, NEG, 5),
    ReferenceCase::subnormal(NEG, 6, -5, NEG, 6),
    ReferenceCase::subnormal(NEG, 7, -5, NEG, 7),
    ReferenceCase::normal(NEG, 8, -5, NEG, 8, -2),
    ReferenceCase::normal(NEG, 9, -5, NEG, 9, -2),
    ReferenceCase::normal(NEG, 10, -5, NEG, 10, -2),
    ReferenceCase::normal(NEG, 11, -5, NEG, 11, -2),
    ReferenceCase::normal(NEG, 12, -5, NEG, 12, -2),
    ReferenceCase::normal(NEG, 13, -5, NEG, 13, -2),
    ReferenceCase::normal(NEG, 14, -5, NEG, 14, -2),
    ReferenceCase::normal(NEG, 15, -5, NEG, 14, -2),
    ReferenceCase::normal(NEG, 8, -4, NEG, 15, -2),
    ReferenceCase::normal(NEG, 9, -4, NEG, 9, -1),
    ReferenceCase::normal(NEG, 10, -4, NEG, 9, -1),
    ReferenceCase::normal(NEG, 11, -4, NEG, 10, -1),
    ReferenceCase::normal(NEG, 12, -4, NEG, 11, -1),
    ReferenceCase::normal(NEG, 13, -4, NEG, 12, -1),
    ReferenceCase::normal(NEG, 14, -4, NEG, 12, -1),
    ReferenceCase::normal(NEG, 15, -4, NEG, 13, -1),
    ReferenceCase::normal(NEG, 8, -3, NEG, 13, -1),
    ReferenceCase::normal(NEG, 9, -3, NEG, 14, -1),
    ReferenceCase::normal(NEG, 10, -3, NEG, 15, -1),
    ReferenceCase::normal(NEG, 11, -3, NEG, 8, 0),
    ReferenceCase::normal(NEG, 12, -3, NEG, 8, 0),
    ReferenceCase::normal(NEG, 13, -3, NEG, 8, 0),
    ReferenceCase::normal(NEG, 14, -3, NEG, 8, 0),
    ReferenceCase::normal(NEG, 15, -3, NEG, 15, -1),
    ReferenceCase::normal(NEG, 8, -2, NEG, 15, -1),
    ReferenceCase::normal(NEG, 9, -2, NEG, 12, -1),
    ReferenceCase::normal(NEG, 10, -2, NEG, 10, -1),
    ReferenceCase::normal(NEG, 11, -2, NEG, 12, -2),
    ReferenceCase::subnormal(NEG, 12, -2, NEG, 5),
    ReferenceCase::subnormal(NEG, 13, -2, POS, 3),
    ReferenceCase::normal(NEG, 14, -2, POS, 11, -2),
    ReferenceCase::normal(NEG, 15, -2, POS, 9, -1),
    ReferenceCase::normal(NEG, 8, -1, POS, 12, -1),
    ReferenceCase::normal(NEG, 9, -1, POS, 8, 0),
    ReferenceCase::normal(NEG, 10, -1, POS, 15, -1),
    ReferenceCase::normal(NEG, 11, -1, POS, 11, -1),
    ReferenceCase::normal(NEG, 12, -1, POS, 9, -2),
    ReferenceCase::subnormal(NEG, 13, -1, NEG, 7),
    ReferenceCase::normal(NEG, 14, -1, NEG, 11, -1),
    ReferenceCase::normal(NEG, 15, -1, NEG, 15, -1),
];

const STRESS_CASES: &[ReferenceCase] = &[
    // minimum subnormal
    ReferenceCase::subnormal(POS, 1, -35, POS, 1),
    // minimum normal
    ReferenceCase::normal(POS, 1, -20, POS, 32768, -20),
    // ordinary one
    ReferenceCase::normal(POS, 1, 0, POS, 55147, -1),
    // ordinary three
    ReferenceCase::normal(POS, 3, 0, POS, 36994, -3),
    // ordinary ten
    ReferenceCase::normal(POS, 10, 0, NEG, 35653, -1),
    // negative ordinary ten
    ReferenceCase::normal(NEG, 10, 0, POS, 35653, -1),
    // range reduction 2^50
    ReferenceCase::normal(POS, 1, 50, POS, 65064, -2),
    // range reduction 2^100
    ReferenceCase::normal(POS, 1, 100, NEG, 57159, -1),
    // range reduction 2^180
    ReferenceCase::normal(POS, 1, 180, POS, 65515, -1),
    // near maximum finite input
    ReferenceCase::normal(POS, 65535, 185, POS, 49234, -3),
    // near midpoint A
    ReferenceCase::normal(POS, 57112, 163, POS, 51253, -5),
    // near midpoint B
    ReferenceCase::normal(POS, 35938, 6, POS, 61886, -3),
    // near midpoint C
    ReferenceCase::normal(POS, 41026, -4, POS, 36210, -1),
];
// END GENERATED SINE REFERENCE CORPUS

fn tiny_format() -> BinaryFormat {
    BinaryFormat::new(4, -2, 2).expect("valid tiny reference format")
}

fn stress_format() -> BinaryFormat {
    BinaryFormat::new(16, -20, 200).expect("valid stress reference format")
}

fn tiny_finite_domain() -> Vec<ExactDyadic> {
    let mut domain = Vec::with_capacity(94);
    for sign in [POS, NEG] {
        for significand in 1..8 {
            domain.push(ExactDyadic::from_parts(sign, significand, -5));
        }
        for exponent in -2..=2 {
            for significand in 8..16 {
                domain.push(ExactDyadic::from_parts(sign, significand, exponent - 3));
            }
        }
    }
    domain
}

fn exact_value_of_encoded(precision: u32, emin: i32, value: RoundedBinaryValue) -> ExactDyadic {
    let precision_tail = i32::try_from(precision - 1).expect("fixture precision fits i32");
    match value {
        RoundedBinaryValue::Subnormal { sign, significand } => {
            ExactDyadic::from_parts(sign, significand, emin - precision_tail)
        }
        RoundedBinaryValue::Normal {
            sign,
            significand,
            exponent,
        } => ExactDyadic::from_parts(sign, significand, exponent - precision_tail),
        RoundedBinaryValue::Zero(_) | RoundedBinaryValue::Infinity(_) => {
            panic!("finite sine corpus must contain only nonzero finite outputs")
        }
    }
}

fn assert_reference_output_is_target_value(
    format: BinaryFormat,
    precision: u32,
    emin: i32,
    case: ReferenceCase,
) {
    let exact = exact_value_of_encoded(precision, emin, case.expected);
    assert_eq!(
        round_dyadic(format, exact),
        Ok(case.expected),
        "reference output is not an exact value of its target format for input {:?}",
        case.input
    );
}

#[test]
fn tiny_reference_corpus_covers_every_signed_nonzero_finite_value_once() {
    let domain = tiny_finite_domain();
    assert_eq!(domain.len(), 94);
    assert_eq!(TINY_FINITE_CASES.len(), domain.len());

    for input in domain {
        let occurrences = TINY_FINITE_CASES
            .iter()
            .filter(|case| case.input == input)
            .count();
        assert_eq!(
            occurrences, 1,
            "tiny reference input {:?} must occur exactly once",
            input
        );
    }
}

#[test]
fn finite_reference_outputs_are_exact_target_format_values() {
    for &case in TINY_FINITE_CASES {
        assert_reference_output_is_target_value(tiny_format(), 4, -2, case);
    }
    for &case in STRESS_CASES {
        assert_reference_output_is_target_value(stress_format(), 16, -20, case);
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum SpecialSineReference {
    Value(RoundedBinaryValue),
    NaNClass,
}

fn special_sine_reference(input: BinaryValueFixture) -> Option<SpecialSineReference> {
    match input {
        BinaryValueFixture::Zero(sign) => {
            Some(SpecialSineReference::Value(RoundedBinaryValue::Zero(sign)))
        }
        BinaryValueFixture::Infinity(_) | BinaryValueFixture::NaNClass => {
            Some(SpecialSineReference::NaNClass)
        }
        BinaryValueFixture::Finite(_) => None,
    }
}

#[test]
fn special_value_reference_matches_accepted_sine_classes() {
    assert_eq!(
        special_sine_reference(BinaryValueFixture::Zero(POS)),
        Some(SpecialSineReference::Value(RoundedBinaryValue::Zero(POS)))
    );
    assert_eq!(
        special_sine_reference(BinaryValueFixture::Zero(NEG)),
        Some(SpecialSineReference::Value(RoundedBinaryValue::Zero(NEG)))
    );
    assert_eq!(
        special_sine_reference(BinaryValueFixture::Infinity(POS)),
        Some(SpecialSineReference::NaNClass)
    );
    assert_eq!(
        special_sine_reference(BinaryValueFixture::Infinity(NEG)),
        Some(SpecialSineReference::NaNClass)
    );
    assert_eq!(
        special_sine_reference(BinaryValueFixture::NaNClass),
        Some(SpecialSineReference::NaNClass)
    );
}
